spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-34-225-159-178.compute-1.amazonaws.com:5432/d4l147rlit45ud
    username: lajljycggptmac
    password: ea5477ed0b0ad038e1931e88360ae0b98c897a99a3252caad7bd99315c73a60e

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080